### ISSUE TITLE
Mails are not being sent on try/staging

### ISSUE THREAD

**Issue by bwgpro** [pixelated-project/pixelated-platform#100] opened 2015-06-15 21:55 UTC
Today we had problems sending emails on try and staging, the error is the same on both and looks like a new issue.

```
Jun 15 19:18:33 pixelated postfix/smtpd[18084]: NOQUEUE: reject: RCPT from unknown[0.0.0.0]: 451 4.3.5 <behave-testuser@staging.pixelated-project.org>: Recipient address rejected: Server configuration error; from=<behave-testuser@staging.pixelated-project.org> to=<behave-testuser@staging.pixelated-project.org> proto=ESMTP helo=<go-agent5.dfi.local>
```

**Comment by varac** [comment] 2015-06-16 10:10
this looks like it is related to [Table lookup problem when sending mail from outside](https://leap.se/code/issues/7157)

**Comment by varac** [comment] 2015-06-16 15:44
after looking more closely, i think this is *not* related to above leap-mx error (cause i don't see any lookups logged in /var/log/leap/mx.log when sending a mail.

**Comment by bwgpro** [comment] 2015-06-16 16:30
I tried to take a look at postfix to see if there was any error but without success, does leap mx also log sending mails instead of only receiving?

**Comment by tiagoferraz** [comment] 2015-06-16 18:18
No code alteration in user agent is capable of doing this, the possible cause is libs, since it was also installing incompatible lib before, this must be another incompatible lib.

**Comment by cz8s** [comment] 2015-06-18 07:31
I just did a clean user-agent installation (vagrant destroy; vagrant up) on my local machine. And that has the same problem. It looks like the user-agent doesn't even try to talk to the leap platform.
This is the error I get:
```
2015-06-18 07:29:02 [pixelated.bitmask_libraries.smtp] WARNING Couldn't start the SMTP server now, will try again when the user tries to use it
```

**Comment by cz8s** [comment] 2015-06-18 07:35
I just realized, these are two totally different problems. I will open a new issue for the user-agent problem.

**Comment by cz8s** [comment] 2015-06-18 07:55
I could send emails to try and staging via smtp. Postfix accepted the mails and sent them to the users inbox. try does not have the behave-testuser, but sending to eve works. @tiagoferraz: Could you test your script again?

**Comment by bwgpro** [comment] 2015-06-18 21:14
This is probably caused because of pixelated-project/pixelated-user-agent#415, the client was not able to download the SMTP certificate and I think the server was denying the connection without the certificate, I would like to have a better error handling in this case, but this should work now

**Comment by cz8s** [comment] 2015-06-22 15:28
The original error was ```Recipient address rejected: Server configuration error```.
This does not sound like the user-agent having problems. But since I couldn't reproduce the error,
I am in favor of closing this issue

**Closed** 2015-06-23 12:59 UTC
Labels: bug
