### ISSUE TITLE
ignore leap soledad client warning on non existing secret file

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-platform#83] opened 2015-04-22 11:51 UTC
# reproduce
install pixelated platform on new server.
sign up as any user
log in with that user
after initial sync, login to nagios

You will find var/log/sys.log in critical state like this:
```
C Apr 14 20:13:23 0cfc5edce2ac ujgzbnms[20978] [04-14 20:13:23] 0cfc5edce2ac leap.soledad.client WARNING IOError: File does not exist: /mnt/user/soledad/57c6dd2bbe5da553eac9c26d1fe0b31f.secret
```

# expected
Since we know that the file is only present after first sync, we want to ignore this error.
If I follow the above steps, I do NOT want to see the critical state message on nagios.

**Comment by tiagoferraz** [comment] 2015-04-22 12:48
@lieblingswelt I agree with you, but should not this be done on Leap side? I am afraid that modifications in Leap code in the future plus this fix we may cover some defects and take sometime to discover the root cause.  What do you think?

**Comment by lieblingswelt** [comment] 2015-04-22 13:45
Yes, fixing the root cause would be good. Speaking to varac, as far as I understood, this is definitely not to be a priority on the leap side for now. So I would opt for ignoring the error on our side for now, so we dont get confused.

**Comment by varac** [comment] 2015-04-22 19:08
the upstream issue is https://leap.se/code/issues/6892, and as meskio said it's not important for LEAP to fix. So we should do it on our side.

**Comment by rafaelzlisboa** [comment] 2015-04-23 16:57
in `soledad/client/secrets.py:253`:

```python
                logger.warning(
                    'IOError while loading secrets from disk: %s' % str(e))
```

I guess we could change this to info instead of warning, since it will always try to get or generate the secret if it's not there?

**Comment by bwgpro** [comment] 2015-04-23 17:09
Yes, I've saw that and even changed locally to test, that should be info. We should see if that is still there on the latest soledad code

**Comment by re-nobre** [comment] 2015-07-29 18:01
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.

**Closed by re-nobre** 2015-07-29 18:01 UTC
Labels: 0 - Backlog

**Comment by varac** [comment] 2015-08-11 11:30
https://leap.se/code/issues/6892 is resolved and the fix is merged.
